id: UploadFile Test
version: -1
name: UploadFile Test
description: Test file uploading to incident with and without comments.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 59df6007-31bf-47f5-84fc-2f47f1848392
    type: start
    task:
      id: 59df6007-31bf-47f5-84fc-2f47f1848392
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 9c0484b4-cfaf-4eee-88c6-ee6e3028ed15
    type: regular
    task:
      id: 9c0484b4-cfaf-4eee-88c6-ee6e3028ed15
      version: -1
      name: Download Image and Add to Context
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      filename:
        simple: image.png
      method:
        simple: GET
      saveAsFile:
        simple: "yes"
      unsecure:
        simple: "true"
      url:
        simple: https://github.com/demisto/content/raw/master/xsoar_content_logo.png
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 727d975a-97f7-4e65-809f-31aae5450fe4
    type: regular
    task:
      id: 727d975a-97f7-4e65-809f-31aae5450fe4
      version: -1
      name: Upload Downloaded File to War Room
      description: Copies a file from this incident to the specified incident. The
        file is recorded as an entry in the specified incident’s War Room.
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: image.png
          accessor: EntryID
      incID:
        simple: ${CreatedIncidentID}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: a24fa9ad-a067-4785-86c5-03a710f701bd
    type: regular
    task:
      id: a24fa9ad-a067-4785-86c5-03a710f701bd
      version: -1
      name: createNewIncident
      description: Create a new incident
      script: Builtin|||createNewIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      name:
        simple: DemistoUploadFile - test incident
      type:
        simple: Xpanse Alert
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 1ebafcaf-f6ef-438f-8a17-ea4010fcdc3d
    type: regular
    task:
      id: 1ebafcaf-f6ef-438f-8a17-ea4010fcdc3d
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: d6301ab6-5e91-49eb-8bb8-c88c097e4165
    type: regular
    task:
      id: d6301ab6-5e91-49eb-8bb8-c88c097e4165
      version: -1
      name: getContext
      description: Retrieve context of another incident to be used in this script
      script: Builtin|||getContext
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
      - "11"
    scriptarguments:
      extend-context:
        simple: FileWithoutCommentEntryID=context.File.[0].EntryID::FileWithCommentEntryID=context.File.[1].EntryID
      id:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: b95f9c94-4b9e-4488-84cf-201e0f0ab7fa
    type: condition
    task:
      id: b95f9c94-4b9e-4488-84cf-201e0f0ab7fa
      version: -1
      name: Verify upload was successful
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              complex:
                root: FileWithoutComment
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: FileWithComment
            iscontext: true
          right:
            value:
              simple: Test Comment
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 6ed2b841-1259-4d02-815a-7a11ccec5e6b
    type: title
    task:
      id: 6ed2b841-1259-4d02-815a-7a11ccec5e6b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: f208b0b8-5d70-4fa5-8393-fe513904142e
    type: regular
    task:
      id: f208b0b8-5d70-4fa5-8393-fe513904142e
      version: -1
      name: Upload Downloaded File to War Room with a Comment
      description: Copies a file from this incident to the specified incident. The
        file is recorded as an entry in the specified incident’s War Room.
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      body:
        simple: '{"fileComment": "Test Comment"}'
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: image.png
          accessor: EntryID
      incID:
        simple: ${CreatedIncidentID}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 7b98e101-3d8f-4d20-8490-227da931bf65
    type: regular
    task:
      id: 7b98e101-3d8f-4d20-8490-227da931bf65
      version: -1
      name: Get File Comment (File With Comment)
      description: send HTTP GET requests
      script: '|||core-api-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      extend-context:
        simple: FileWithComment=response.contents
      uri:
        complex:
          root: FileWithCommentEntryID
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: /
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: CreatedIncidentID
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: /entry/load/
              suffix: {}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 57157ab4-6d8c-45da-892b-2956d3ab8a7e
    type: regular
    task:
      id: 57157ab4-6d8c-45da-892b-2956d3ab8a7e
      version: -1
      name: Get File Comment (File Without Comment)
      description: send HTTP GET requests
      script: '|||core-api-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      extend-context:
        simple: FileWithoutComment=response.contents
      uri:
        complex:
          root: FileWithoutCommentEntryID
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: /
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: CreatedIncidentID
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: /entry/load/
              suffix: {}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 0df5d40a-3f2e-4d53-85b2-8e2547aaa981
    type: regular
    task:
      id: 0df5d40a-3f2e-4d53-85b2-8e2547aaa981
      version: -1
      name: Sleep 20 sec
      description: Sleep for X seconds.
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      seconds:
        simple: "20"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.0.0
