id: DemistoUploadFileV2 Test
version: -1
name: DemistoUploadFileV2 Test
description: Test file uploading to incident with and without comments.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3df181e7-d658-4c63-8e42-841502adce32
    type: start
    task:
      id: 3df181e7-d658-4c63-8e42-841502adce32
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 16438ac4-b962-4c44-8c39-6806dd4f23bf
    type: regular
    task:
      id: 16438ac4-b962-4c44-8c39-6806dd4f23bf
      version: -1
      name: Download Image and Add to Context
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      filename:
        simple: image.png
      method:
        simple: GET
      saveAsFile:
        simple: "yes"
      unsecure:
        simple: "true"
      url:
        simple: https://github.com/demisto/content/raw/master/xsoar_content_logo.png
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 36e8ff4a-8776-4575-8d3b-b30d67fb0953
    type: regular
    task:
      id: 36e8ff4a-8776-4575-8d3b-b30d67fb0953
      version: -1
      name: Upload Downloaded File to War Room
      description: Upload file from incident war room to another incident's war room
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: image.png
          accessor: EntryID
      execution-timeout:
        simple: "6000"
      incID:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 0a2915ab-6e4d-47b3-88de-ba6e75e8cd30
    type: regular
    task:
      id: 0a2915ab-6e4d-47b3-88de-ba6e75e8cd30
      version: -1
      name: createNewIncident
      description: Create a new incident
      script: Builtin|||createNewIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      name:
        simple: DemistoUploadFile - test incident
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 33835af5-5d26-4b87-8027-6702f65cdfdd
    type: regular
    task:
      id: 33835af5-5d26-4b87-8027-6702f65cdfdd
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: b91ddc50-3fd9-48f6-8811-8a0871ae33fc
    type: regular
    task:
      id: b91ddc50-3fd9-48f6-8811-8a0871ae33fc
      version: -1
      name: getContext
      description: Retrieve context of another incident to be used in this script
      script: Builtin|||getContext
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
      - "11"
    scriptarguments:
      extend-context:
        simple: FileWithoutCommentEntryID=context.File.[0].EntryID::FileWithCommentEntryID=context.File.[1].EntryID
      id:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: bd82b60c-5262-47d2-87bd-cb1a36f54aa5
    type: condition
    task:
      id: bd82b60c-5262-47d2-87bd-cb1a36f54aa5
      version: -1
      name: Verify upload was successful
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              complex:
                root: FileWithoutComment
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: FileWithComment
            iscontext: true
          right:
            value:
              simple: Test Comment
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 39c4f57b-edb1-4205-8e0f-72903f051603
    type: title
    task:
      id: 39c4f57b-edb1-4205-8e0f-72903f051603
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1795
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 4db2b341-5fd4-456d-8c48-945d58649791
    type: regular
    task:
      id: 4db2b341-5fd4-456d-8c48-945d58649791
      version: -1
      name: Upload Downloaded File to War Room with a Comment
      description: Upload file from incident war room to another incident's war room
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      body:
        simple: '{"fileComment": "Test Comment"}'
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: image.png
          accessor: EntryID
      execution-timeout:
        simple: "3600"
      incID:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1045
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 541c2523-ae9b-4de8-8aff-0675d1727b00
    type: regular
    task:
      id: 541c2523-ae9b-4de8-8aff-0675d1727b00
      version: -1
      name: Get File Comment (File With Comment)
      description: send HTTP GET requests
      script: '|||core-api-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      extend-context:
        simple: FileWithComment=response.contents
      uri:
        complex:
          root: FileWithCommentEntryID
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: /
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: CreatedIncidentID
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: /entry/load/
              suffix: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 15f07518-f9d0-40f9-8e3c-d9d11635375c
    type: regular
    task:
      id: 15f07518-f9d0-40f9-8e3c-d9d11635375c
      version: -1
      name: Get File Comment (File Without Comment)
      description: send HTTP GET requests
      script: '|||core-api-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      extend-context:
        simple: FileWithoutComment=response.contents
      uri:
        complex:
          root: FileWithoutCommentEntryID
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: /
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: CreatedIncidentID
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: /entry/load/
              suffix: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: c312cb9f-c373-4629-82db-c6841850b869
    type: regular
    task:
      id: c312cb9f-c373-4629-82db-c6841850b869
      version: -1
      name: Sleep for 50 seconds
      description: Sleep for X seconds.
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      seconds:
        simple: "50"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1810,
        "width": 810,
        "x": 60,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.0.0
