id: UploadFile Test
version: -1
name: UploadFile Test
description: Test file uploading to incident with and without comments.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: db29b3d5-bcdf-40bc-8fb8-902d43caba73
    type: start
    task:
      id: db29b3d5-bcdf-40bc-8fb8-902d43caba73
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 940b6990-2b71-448f-8f05-f46267433c55
    type: regular
    task:
      id: 940b6990-2b71-448f-8f05-f46267433c55
      version: -1
      name: Download Image and Add to Context
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      filename:
        simple: image.png
      method:
        simple: GET
      saveAsFile:
        simple: "yes"
      unsecure:
        simple: "true"
      url:
        simple: https://github.com/demisto/content/raw/master/xsoar_content_logo.png
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 1494360f-0e1e-4495-8e11-3fc818bb98aa
    type: regular
    task:
      id: 1494360f-0e1e-4495-8e11-3fc818bb98aa
      version: -1
      name: Upload Downloaded File to War Room
      description: Copies a file from this incident to the specified incident. The file is recorded as an entry in the specified incident’s War Room.
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: image.png
          accessor: EntryID
      incID:
        simple: ${CreatedIncidentID}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 4e80eafd-7bf1-439c-8e5e-e40ef7144461
    type: regular
    task:
      id: 4e80eafd-7bf1-439c-8e5e-e40ef7144461
      version: -1
      name: createNewIncident
      description: Create a new incident
      script: Builtin|||createNewIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      name:
        simple: DemistoUploadFile - test incident
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: f5c1b3a8-15dc-4125-826e-c8662cab7e2f
    type: regular
    task:
      id: f5c1b3a8-15dc-4125-826e-c8662cab7e2f
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 630de333-ec32-4b9d-8168-114a6eaa4721
    type: regular
    task:
      id: 630de333-ec32-4b9d-8168-114a6eaa4721
      version: -1
      name: getContext
      description: Retrieve context of another incident to be used in this script
      script: Builtin|||getContext
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
      - "11"
    scriptarguments:
      extend-context:
        simple: FileWithoutCommentEntryID=context.File.[0].EntryID::FileWithCommentEntryID=context.File.[1].EntryID
      id:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 765a4b8a-e04c-4286-8a7e-b2695fefd2fc
    type: condition
    task:
      id: 765a4b8a-e04c-4286-8a7e-b2695fefd2fc
      version: -1
      name: Verify upload was successful
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              complex:
                root: FileWithoutComment
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: FileWithComment
            iscontext: true
          right:
            value:
              simple: Test Comment
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: add6a00a-fc13-41bb-879e-e825d394a3e2
    type: title
    task:
      id: add6a00a-fc13-41bb-879e-e825d394a3e2
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: d6dba1ba-4af6-41cc-8cd9-2aa3d8fe6c8c
    type: regular
    task:
      id: d6dba1ba-4af6-41cc-8cd9-2aa3d8fe6c8c
      version: -1
      name: Upload Downloaded File to War Room with a Comment
      description: Copies a file from this incident to the specified incident. The file is recorded as an entry in the specified incident’s War Room.
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      body:
        simple: '{"fileComment": "Test Comment"}'
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: image.png
          accessor: EntryID
      incID:
        simple: ${CreatedIncidentID}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: b1d80a37-bd3e-4728-826c-7447425cbf5d
    type: regular
    task:
      id: b1d80a37-bd3e-4728-826c-7447425cbf5d
      version: -1
      name: Get File Comment (File With Comment)
      description: send HTTP GET requests
      script: '|||core-api-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      extend-context:
        simple: FileWithComment=response.contents
      uri:
        complex:
          root: FileWithCommentEntryID
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: /
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: CreatedIncidentID
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: /entry/load/
              suffix: {}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: ba44f3e1-3c23-4710-8591-476c81d1a27c
    type: regular
    task:
      id: ba44f3e1-3c23-4710-8591-476c81d1a27c
      version: -1
      name: Get File Comment (File Without Comment)
      description: send HTTP GET requests
      script: '|||core-api-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      extend-context:
        simple: FileWithoutComment=response.contents
      uri:
        complex:
          root: FileWithoutCommentEntryID
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: /
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: CreatedIncidentID
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: /entry/load/
              suffix: {}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 359b53c1-e074-41a8-87cc-7b1aeaa63a21
    type: regular
    task:
      id: 359b53c1-e074-41a8-87cc-7b1aeaa63a21
      version: -1
      name: Activate the incident investigation
      script: investigate
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      id:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: c32cf7ff-a039-48ae-85f5-c75213f17f84
    type: regular
    task:
      id: c32cf7ff-a039-48ae-85f5-c75213f17f84
      version: -1
      name: Sleep 20 sec
      description: Sleep for X seconds.
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      seconds:
        simple: "20"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 2b1b2f87-7b71-4b06-8515-1a7b20d229af
    type: regular
    task:
      id: 2b1b2f87-7b71-4b06-8515-1a7b20d229af
      version: -1
      name: Sleep 20 sec
      description: Sleep for X seconds.
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      seconds:
        simple: "20"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.0.0
