id: UploadFile Test
version: 11
vcShouldKeepItemLegacyProdMachine: false
name: UploadFile Test
description: Test file uploading to incident with and without comments.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6bad2430-3999-4ce5-858a-a2034d1706ac
    type: start
    task:
      id: 6bad2430-3999-4ce5-858a-a2034d1706ac
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 0e6c28b4-80c4-49e8-84ce-03017f108f29
    type: regular
    task:
      id: 0e6c28b4-80c4-49e8-84ce-03017f108f29
      version: -1
      name: Download Image and Add to Context
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      filename:
        simple: image.png
      method:
        simple: GET
      saveAsFile:
        simple: "yes"
      unsecure:
        simple: "true"
      url:
        simple: https://github.com/demisto/content/raw/master/xsoar_content_logo.png
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 32474d8a-9fbf-4e09-8553-41e360e33651
    type: regular
    task:
      id: 32474d8a-9fbf-4e09-8553-41e360e33651
      version: -1
      name: Upload Downloaded File to War Room
      description: Copies a file from this incident to the specified incident. The
        file is recorded as an entry in the specified incident’s War Room.
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: image.png
          accessor: EntryID
      incID:
        simple: ${CreatedIncidentID}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: cdf7149e-1982-44ac-8222-9809a213b2f8
    type: regular
    task:
      id: cdf7149e-1982-44ac-8222-9809a213b2f8
      version: -1
      name: createNewIncident
      description: Create a new incident
      script: Builtin|||createNewIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      name:
        simple: DemistoUploadFile - test incident
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 82c1c18a-4acb-482a-845a-33a80b7fe397
    type: regular
    task:
      id: 82c1c18a-4acb-482a-845a-33a80b7fe397
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 9b6abe42-2fdf-43c5-83f8-ab8ff4bae0d6
    type: regular
    task:
      id: 9b6abe42-2fdf-43c5-83f8-ab8ff4bae0d6
      version: -1
      name: getContext
      description: Retrieve context of another incident to be used in this script
      script: Builtin|||getContext
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
      - "11"
    scriptarguments:
      extend-context:
        simple: FileWithoutCommentEntryID=context.File.[0].EntryID::FileWithCommentEntryID=context.File.[1].EntryID
      id:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 10fa2f89-1377-4a86-88f4-6ec6ed3acdb3
    type: condition
    task:
      id: 10fa2f89-1377-4a86-88f4-6ec6ed3acdb3
      version: -1
      name: Verify upload was successful
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              complex:
                root: FileWithoutComment
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: FileWithComment
            iscontext: true
          right:
            value:
              simple: Test Comment
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 47ab951f-f906-4581-8894-2f03db7d83ab
    type: title
    task:
      id: 47ab951f-f906-4581-8894-2f03db7d83ab
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 09e905e7-1cfc-43af-835f-83b5021780c1
    type: regular
    task:
      id: 09e905e7-1cfc-43af-835f-83b5021780c1
      version: -1
      name: Upload Downloaded File to War Room with a Comment
      description: Copies a file from this incident to the specified incident. The
        file is recorded as an entry in the specified incident’s War Room.
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      body:
        simple: '{"fileComment": "Test Comment"}'
      entryID:
        complex:
          root: File
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: image.png
          accessor: EntryID
      incID:
        simple: ${CreatedIncidentID}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 6d8f77c0-901f-4f48-8ab9-29d32c0dfe92
    type: regular
    task:
      id: 6d8f77c0-901f-4f48-8ab9-29d32c0dfe92
      version: -1
      name: Get File Comment (File With Comment)
      description: send HTTP GET requests
      script: '|||core-api-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      extend-context:
        simple: FileWithComment=response.contents
      uri:
        complex:
          root: FileWithCommentEntryID
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: /
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: CreatedIncidentID
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: /entry/load/
              suffix: {}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 67b6c3bb-b4fd-4f06-8247-c5695db0f2db
    type: regular
    task:
      id: 67b6c3bb-b4fd-4f06-8247-c5695db0f2db
      version: -1
      name: Get File Comment (File Without Comment)
      description: send HTTP GET requests
      script: '|||core-api-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      extend-context:
        simple: FileWithoutComment=response.contents
      uri:
        complex:
          root: FileWithoutCommentEntryID
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: /
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: CreatedIncidentID
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: /entry/load/
              suffix: {}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: ebdc29c5-99c1-4a4b-8d4d-141b65fde9b4
    type: regular
    task:
      id: ebdc29c5-99c1-4a4b-8d4d-141b65fde9b4
      version: -1
      name: Activate the incident investigation
      script: investigate
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      id:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
dirtyInputs: true
