id: TAXII2 Performance Test - Concurrency
version: -1
name: TAXII2 Performance Test - Concurrency
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 263d81f0-60c6-4d82-8ee5-b1e5d9173557
    type: start
    task:
      id: 263d81f0-60c6-4d82-8ee5-b1e5d9173557
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "1":
    id: "1"
    taskid: bfc43620-d01a-4701-85e5-702f9fbad013
    type: title
    task:
      id: bfc43620-d01a-4701-85e5-702f9fbad013
      version: -1
      name: Concurrency 1
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "3":
    id: "3"
    taskid: 734ec090-da07-42f2-855f-7d302e715723
    type: title
    task:
      id: 734ec090-da07-42f2-855f-7d302e715723
      version: -1
      name: Concurrency 10
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "6":
    id: "6"
    taskid: 5989e654-f19c-4ffe-8e45-c4afd4054b38
    type: title
    task:
      id: 5989e654-f19c-4ffe-8e45-c4afd4054b38
      version: -1
      name: Concurrency 20
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "8":
    id: "8"
    taskid: 7aa168ef-16a9-43a8-8808-6fc6cf16a9aa
    type: title
    task:
      id: 7aa168ef-16a9-43a8-8808-6fc6cf16a9aa
      version: -1
      name: Concurrency 100
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2205
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "11":
    id: "11"
    taskid: d2150ac8-78c1-4713-8185-edd93a0b1e7e
    type: title
    task:
      id: d2150ac8-78c1-4713-8185-edd93a0b1e7e
      version: -1
      name: Concurrency 200
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2875
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "12":
    id: "12"
    taskid: 218bcd1a-10fb-4406-8e58-527889da1f23
    type: playbook
    task:
      id: 218bcd1a-10fb-4406-8e58-527889da1f23
      version: -1
      name: TAXII2 Indicator Performance Test
      playbookName: TAXII2 Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      c:
        simple: "1"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "0"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
      base64_of_the_test_password:
        simple: ${inputs.base64_of_the_test_password}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "13":
    id: "13"
    taskid: 49de863c-d837-4798-8bd6-6c2b317be83e
    type: playbook
    task:
      id: 49de863c-d837-4798-8bd6-6c2b317be83e
      version: -1
      name: TAXII2 Indicator Performance Test
      playbookName: TAXII2 Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      c:
        simple: "10"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "2"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
      base64_of_the_test_password:
        simple: ${inputs.base64_of_the_test_password}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "14":
    id: "14"
    taskid: 925c26c6-86f0-4e80-8e56-127cb71f5abd
    type: playbook
    task:
      id: 925c26c6-86f0-4e80-8e56-127cb71f5abd
      version: -1
      name: TAXII2 Indicator Performance Test
      playbookName: TAXII2 Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      c:
        simple: "20"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "2"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
      base64_of_the_test_password:
        simple: ${inputs.base64_of_the_test_password}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "15":
    id: "15"
    taskid: e963ad50-67f0-4c94-872f-3e57c4ff9c01
    type: playbook
    task:
      id: e963ad50-67f0-4c94-872f-3e57c4ff9c01
      version: -1
      name: TAXII2 Indicator Performance Test
      playbookName: TAXII2 Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      c:
        simple: "100"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "3"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
      base64_of_the_test_password:
        simple: ${inputs.base64_of_the_test_password}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "16":
    id: "16"
    taskid: 3fb25dad-c126-48d1-8ffe-8fce927c9da8
    type: playbook
    task:
      id: 3fb25dad-c126-48d1-8ffe-8fce927c9da8
      version: -1
      name: TAXII2 Indicator Performance Test
      playbookName: TAXII2 Indicator Performance Test
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      c:
        simple: "200"
      "n":
        simple: ${inputs.n}
      results_map:
        simple: ${inputs.results_map}
      t:
        simple: "0"
      url:
        complex:
          root: inputs.url
      z:
        simple: ${inputs.z}
      base64_of_the_test_password:
        simple: ${inputs.base64_of_the_test_password}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3020
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "17":
    id: "17"
    taskid: 3b38dcfb-bb4d-488d-83eb-7622321eb6e8
    type: regular
    task:
      id: 3b38dcfb-bb4d-488d-83eb-7622321eb6e8
      version: -1
      name: Set HeyConcurrency
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      key:
        simple: HeyConcurrency
      value:
        simple: ${Hey}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "18":
    id: "18"
    taskid: 65209b10-ed5e-4e58-8e74-ae4e829545a2
    type: regular
    task:
      id: 65209b10-ed5e-4e58-8e74-ae4e829545a2
      version: -1
      name: Clear Hey Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Hey
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "19":
    id: "19"
    taskid: c7cfc48b-72d6-4f65-8b5c-bb88c3498101
    type: regular
    task:
      id: c7cfc48b-72d6-4f65-8b5c-bb88c3498101
      version: -1
      name: Set HeyConcurrency
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: HeyConcurrency
      value:
        simple: ${Hey}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1185
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "20":
    id: "20"
    taskid: e5d4c9f1-602c-4c17-87c4-3aee17ca3742
    type: regular
    task:
      id: e5d4c9f1-602c-4c17-87c4-3aee17ca3742
      version: -1
      name: Clear Hey Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Hey
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "21":
    id: "21"
    taskid: aee199ed-e8e1-4531-8867-c77bb9377941
    type: regular
    task:
      id: aee199ed-e8e1-4531-8867-c77bb9377941
      version: -1
      name: Set HeyConcurrency
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: HeyConcurrency
      value:
        simple: ${Hey}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1855
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "22":
    id: "22"
    taskid: bdba4507-1d5c-454e-8583-28e310f537db
    type: regular
    task:
      id: bdba4507-1d5c-454e-8583-28e310f537db
      version: -1
      name: Clear Hey Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Hey
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2030
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "23":
    id: "23"
    taskid: b24555fc-7b31-4c62-8dd7-76dd0735c37f
    type: regular
    task:
      id: b24555fc-7b31-4c62-8dd7-76dd0735c37f
      version: -1
      name: Set HeyConcurrency
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: HeyConcurrency
      value:
        simple: ${Hey}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2525
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "24":
    id: "24"
    taskid: 9709b065-99b2-48cf-8e85-a8e5c803684e
    type: regular
    task:
      id: 9709b065-99b2-48cf-8e85-a8e5c803684e
      version: -1
      name: Clear Hey Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Hey
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "25":
    id: "25"
    taskid: d26dba59-c69e-4363-87df-512fe72638aa
    type: regular
    task:
      id: d26dba59-c69e-4363-87df-512fe72638aa
      version: -1
      name: Set HeyConcurrency
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: HeyConcurrency
      value:
        simple: ${Hey}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
  "26":
    id: "26"
    taskid: fae9e0f8-4800-46f2-8f96-82f9f0343174
    type: regular
    task:
      id: fae9e0f8-4800-46f2-8f96-82f9f0343174
      version: -1
      name: Clear Hey Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: Hey
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
    continueonerrortype: ""
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3415,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: url
  value: {}
  required: false
  description: The URL of the EDL instance with with query in the end
  playbookInputQuery:
- key: results_map
  value: {}
  required: false
  description: ""
  playbookInputQuery:
- key: "n"
  value: {}
  required: false
  description: ""
  playbookInputQuery:
- key: z
  value: {}
  required: false
  description: ""
  playbookInputQuery:
- key: base64_of_the_test_password
  value:
    simple: dGVzdDEyOnRlc3QxMg==
  required: false
  description: The base64 of the test12 password for the TAXII
  playbookInputQuery:
outputs:
- contextPath: HeyConcurrency
  type: unknown
fromversion: 6.1.0
description: ''