variables:
  CURRENT_BRANCH_NAME: "ciac-11298/core_packs_override_pipeline"

include:
  - file: "/.gitlab/ci/content-ci/ci/.gitlab-ci.yml"
    ref: "ciac-11298/core_packs_override_pipeline"
    project: "${CI_PROJECT_NAMESPACE}/infra"
