variables:
  CURRENT_BRANCH_NAME: "bypass-url-label-hotfix"

include:
  - file: "/.gitlab/ci/content-ci/ci/.gitlab-ci.yml"
    ref: "bypass-url-label-hotfix"
    project: "${CI_PROJECT_NAMESPACE}/infra"
